"""initial ticket booking schema

Revision ID: 0001
Revises:
Create Date: 2026-09-21 13:05:44.696479

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "CUSTOMER",
                "ORGANIZER",
                "ADMIN",
                name="userrole",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="CUSTOMER",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email = btrim(email) AND email <> ''", name=op.f("ck_users_email_trimmed")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "audit_logs",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity", "entity_id", "timestamp"], unique=False
    )
    op.create_index("ix_audit_logs_user_time", "audit_logs", ["user_id", "timestamp"], unique=False)
    op.create_table(
        "venues",
        sa.Column("organizer_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint("capacity > 0", name=op.f("ck_venues_capacity_positive")),
        sa.ForeignKeyConstraint(
            ["organizer_id"], ["users.id"], name=op.f("fk_venues_organizer_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_venues")),
        sa.UniqueConstraint("id", "organizer_id", name="uq_venues_id_organizer"),
    )
    op.create_index(op.f("ix_venues_city"), "venues", ["city"], unique=False)
    op.create_index(op.f("ix_venues_organizer_id"), "venues", ["organizer_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("organizer_id", sa.Uuid(), nullable=False),
        sa.Column("venue_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "concert",
                "cinema",
                "conference",
                "football",
                "stand_up",
                "other",
                name="eventcategory",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("event_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PUBLISHED",
                "CANCELLED",
                "FINISHED",
                name="eventstatus",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organizer_id"], ["users.id"], name=op.f("fk_events_organizer_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["venue_id", "organizer_id"],
            ["venues.id", "venues.organizer_id"],
            name=op.f("fk_events_venue_id_venues"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("id", "venue_id", name="uq_events_id_venue"),
    )
    op.create_index("ix_events_category_date", "events", ["category", "event_date"], unique=False)
    op.create_index(op.f("ix_events_organizer_id"), "events", ["organizer_id"], unique=False)
    op.create_index("ix_events_status_date", "events", ["status", "event_date"], unique=False)
    op.create_index(op.f("ix_events_venue_id"), "events", ["venue_id"], unique=False)
    op.create_table(
        "sections",
        sa.Column("venue_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["venue_id"], ["venues.id"], name=op.f("fk_sections_venue_id_venues")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sections")),
        sa.UniqueConstraint("id", "venue_id", name="uq_sections_id_venue"),
        sa.UniqueConstraint("venue_id", "name", name="uq_sections_venue_name"),
    )
    op.create_table(
        "reservation_groups",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now() + interval '10 minutes'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_reservation_groups_expiry_after_creation")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_reservation_groups_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reservation_groups_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservation_groups")),
        sa.UniqueConstraint(
            "id", "user_id", "event_id", "expires_at", name="uq_reservation_groups_shared_expiry"
        ),
        sa.UniqueConstraint("id", "user_id", "event_id", name="uq_reservation_groups_owner_event"),
    )
    op.create_index(
        op.f("ix_reservation_groups_event_id"), "reservation_groups", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_reservation_groups_user_id"), "reservation_groups", ["user_id"], unique=False
    )
    op.create_table(
        "seats",
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("seat_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint("row_number > 0", name=op.f("ck_seats_row_positive")),
        sa.CheckConstraint("seat_number > 0", name=op.f("ck_seats_number_positive")),
        sa.ForeignKeyConstraint(
            ["section_id"], ["sections.id"], name=op.f("fk_seats_section_id_sections")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seats")),
        sa.UniqueConstraint("id", "section_id", name="uq_seats_id_section"),
        sa.UniqueConstraint("section_id", "row_number", "seat_number", name="uq_seats_position"),
    )
    op.create_table(
        "ticket_types",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("venue_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="KZT", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint("currency = 'KZT'", name=op.f("ck_ticket_types_currency_kzt")),
        sa.CheckConstraint(
            "price BETWEEN 0 AND 9999999999.99", name=op.f("ck_ticket_types_price_range")
        ),
        sa.ForeignKeyConstraint(
            ["event_id", "venue_id"],
            ["events.id", "events.venue_id"],
            name=op.f("fk_ticket_types_event_id_events"),
        ),
        sa.ForeignKeyConstraint(
            ["section_id", "venue_id"],
            ["sections.id", "sections.venue_id"],
            name=op.f("fk_ticket_types_section_id_sections"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_types")),
        sa.UniqueConstraint("event_id", "name", name="uq_ticket_types_event_name"),
        sa.UniqueConstraint(
            "id", "event_id", "section_id", name="uq_ticket_types_id_event_section"
        ),
    )
    op.create_index(
        op.f("ix_ticket_types_section_id"), "ticket_types", ["section_id"], unique=False
    )
    op.create_table(
        "event_seats",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("seat_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_type_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["seat_id", "section_id"],
            ["seats.id", "seats.section_id"],
            name=op.f("fk_event_seats_seat_id_seats"),
        ),
        sa.ForeignKeyConstraint(
            ["ticket_type_id", "event_id", "section_id"],
            ["ticket_types.id", "ticket_types.event_id", "ticket_types.section_id"],
            name=op.f("fk_event_seats_ticket_type_id_ticket_types"),
        ),
        sa.PrimaryKeyConstraint("event_id", "seat_id", name=op.f("pk_event_seats")),
        sa.UniqueConstraint("event_id", "seat_id", "ticket_type_id", name="uq_event_seats_tariff"),
    )
    op.create_index(op.f("ix_event_seats_seat_id"), "event_seats", ["seat_id"], unique=False)
    op.create_index(
        op.f("ix_event_seats_ticket_type_id"), "event_seats", ["ticket_type_id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("reservation_group_id", sa.Uuid(), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="KZT", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PAID",
                "CANCELLED",
                "REFUNDED",
                name="orderstatus",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'KZT'", name=op.f("ck_orders_currency_kzt")),
        sa.CheckConstraint(
            "total_amount BETWEEN 0 AND 9999999999.99", name=op.f("ck_orders_total_amount_range")
        ),
        sa.ForeignKeyConstraint(
            ["reservation_group_id", "user_id", "event_id"],
            ["reservation_groups.id", "reservation_groups.user_id", "reservation_groups.event_id"],
            name=op.f("fk_orders_reservation_group_id_reservation_groups"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint(
            "id", "reservation_group_id", "event_id", name="uq_orders_item_reference"
        ),
        sa.UniqueConstraint("reservation_group_id", name=op.f("uq_orders_reservation_group_id")),
    )
    op.create_index(op.f("ix_orders_event_id"), "orders", ["event_id"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "ticket_reservations",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("seat_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "EXPIRED",
                "COMPLETED",
                name="reservationstatus",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id", "seat_id"],
            ["event_seats.event_id", "event_seats.seat_id"],
            name=op.f("fk_ticket_reservations_event_id_event_seats"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id", "user_id", "event_id", "expires_at"],
            [
                "reservation_groups.id",
                "reservation_groups.user_id",
                "reservation_groups.event_id",
                "reservation_groups.expires_at",
            ],
            name=op.f("fk_ticket_reservations_group_id_reservation_groups"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_reservations")),
        sa.UniqueConstraint("group_id", "seat_id", name="uq_ticket_reservations_group_seat"),
        sa.UniqueConstraint(
            "id", "group_id", "event_id", "seat_id", name="uq_ticket_reservations_item_reference"
        ),
    )
    op.create_index(
        "ix_ticket_reservations_expiry",
        "ticket_reservations",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_index(
        op.f("ix_ticket_reservations_user_id"), "ticket_reservations", ["user_id"], unique=False
    )
    op.create_index(
        "uq_ticket_reservations_active_seat",
        "ticket_reservations",
        ["event_id", "seat_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("reservation_group_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("seat_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_type_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_type_name", sa.String(length=100), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="KZT", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint("currency = 'KZT'", name=op.f("ck_order_items_currency_kzt")),
        sa.CheckConstraint(
            "unit_price BETWEEN 0 AND 9999999999.99", name=op.f("ck_order_items_unit_price_range")
        ),
        sa.ForeignKeyConstraint(
            ["event_id", "seat_id", "ticket_type_id"],
            ["event_seats.event_id", "event_seats.seat_id", "event_seats.ticket_type_id"],
            name=op.f("fk_order_items_event_id_event_seats"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id", "reservation_group_id", "event_id"],
            ["orders.id", "orders.reservation_group_id", "orders.event_id"],
            name=op.f("fk_order_items_order_id_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id", "reservation_group_id", "event_id", "seat_id"],
            [
                "ticket_reservations.id",
                "ticket_reservations.group_id",
                "ticket_reservations.event_id",
                "ticket_reservations.seat_id",
            ],
            name=op.f("fk_order_items_reservation_id_ticket_reservations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
        sa.UniqueConstraint(
            "id", "order_id", "event_id", "seat_id", name="uq_order_items_ticket_reference"
        ),
        sa.UniqueConstraint("order_id", "seat_id", name="uq_order_items_order_seat"),
        sa.UniqueConstraint("reservation_id", name=op.f("uq_order_items_reservation_id")),
    )
    op.create_index(
        op.f("ix_order_items_ticket_type_id"), "order_items", ["ticket_type_id"], unique=False
    )
    op.create_table(
        "tickets",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("order_item_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("seat_id", sa.Uuid(), nullable=False),
        sa.Column(
            "qr_code", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "VALID",
                "USED",
                "CANCELLED",
                name="ticketstatus",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="VALID",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_item_id", "order_id", "event_id", "seat_id"],
            [
                "order_items.id",
                "order_items.order_id",
                "order_items.event_id",
                "order_items.seat_id",
            ],
            name=op.f("fk_tickets_order_item_id_order_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
        sa.UniqueConstraint("order_item_id", name=op.f("uq_tickets_order_item_id")),
        sa.UniqueConstraint("qr_code", name=op.f("uq_tickets_qr_code")),
    )
    op.create_index(op.f("ix_tickets_order_id"), "tickets", ["order_id"], unique=False)
    op.create_index(
        "uq_tickets_live_seat",
        "tickets",
        ["event_id", "seat_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('VALID', 'USED')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_tickets_live_seat",
        table_name="tickets",
        postgresql_where=sa.text("status IN ('VALID', 'USED')"),
    )
    op.drop_index(op.f("ix_tickets_order_id"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_order_items_ticket_type_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(
        "uq_ticket_reservations_active_seat",
        table_name="ticket_reservations",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index(op.f("ix_ticket_reservations_user_id"), table_name="ticket_reservations")
    op.drop_index(
        "ix_ticket_reservations_expiry",
        table_name="ticket_reservations",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("ticket_reservations")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_event_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_event_seats_ticket_type_id"), table_name="event_seats")
    op.drop_index(op.f("ix_event_seats_seat_id"), table_name="event_seats")
    op.drop_table("event_seats")
    op.drop_index(op.f("ix_ticket_types_section_id"), table_name="ticket_types")
    op.drop_table("ticket_types")
    op.drop_table("seats")
    op.drop_index(op.f("ix_reservation_groups_user_id"), table_name="reservation_groups")
    op.drop_index(op.f("ix_reservation_groups_event_id"), table_name="reservation_groups")
    op.drop_table("reservation_groups")
    op.drop_table("sections")
    op.drop_index(op.f("ix_events_venue_id"), table_name="events")
    op.drop_index("ix_events_status_date", table_name="events")
    op.drop_index(op.f("ix_events_organizer_id"), table_name="events")
    op.drop_index("ix_events_category_date", table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_venues_organizer_id"), table_name="venues")
    op.drop_index(op.f("ix_venues_city"), table_name="venues")
    op.drop_table("venues")
    op.drop_index("ix_audit_logs_user_time", table_name="audit_logs")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
